/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module get_neighbours_x_39 (
    input clk,
    input rst,
    input [24:0] cursor,
    output reg [24:0] up_left,
    output reg [24:0] down_left,
    output reg [24:0] up_right,
    output reg [24:0] down_right
  );
  
  
  
  reg [1:0] M_ctr_d, M_ctr_q = 1'h0;
  reg [24:0] M_ul_temp_d, M_ul_temp_q = 1'h0;
  reg [24:0] M_dl_temp_d, M_dl_temp_q = 1'h0;
  reg [24:0] M_ur_temp_d, M_ur_temp_q = 1'h0;
  reg [24:0] M_dr_temp_d, M_dr_temp_q = 1'h0;
  reg [4:0] M_cursor_position_d, M_cursor_position_q = 1'h0;
  
  wire [25-1:0] M_alu_out;
  reg [25-1:0] M_alu_a;
  reg [25-1:0] M_alu_b;
  reg [6-1:0] M_alu_alufn;
  alu_37 alu (
    .a(M_alu_a),
    .b(M_alu_b),
    .alufn(M_alu_alufn),
    .out(M_alu_out)
  );
  
  wire [5-1:0] M_get_position_pos;
  reg [25-1:0] M_get_position_cursor;
  get_position_23 get_position (
    .cursor(M_get_position_cursor),
    .pos(M_get_position_pos)
  );
  
  localparam BW_DIAG = 3'h7;
  
  localparam FW_DIAG = 1'h1;
  
  always @* begin
    M_ur_temp_d = M_ur_temp_q;
    M_dl_temp_d = M_dl_temp_q;
    M_dr_temp_d = M_dr_temp_q;
    M_ul_temp_d = M_ul_temp_q;
    M_ctr_d = M_ctr_q;
    M_cursor_position_d = M_cursor_position_q;
    
    M_alu_a = 25'h0000000;
    M_alu_b = 25'h0000000;
    M_alu_alufn = 25'h0000000;
    M_ul_temp_d = M_ul_temp_q;
    M_dl_temp_d = M_dl_temp_q;
    M_ur_temp_d = M_ur_temp_q;
    M_dr_temp_d = M_dr_temp_q;
    M_cursor_position_d = M_cursor_position_q;
    M_get_position_cursor = cursor;
    M_cursor_position_d = M_get_position_pos;
    M_ctr_d = M_ctr_q + 1'h1;
    
    case (M_ctr_q)
      1'h0: begin
        M_alu_a = cursor;
        M_alu_b = 3'h7;
        M_alu_alufn = 6'h20;
        M_ul_temp_d = M_alu_out;
      end
      1'h1: begin
        M_alu_a = cursor;
        M_alu_b = 1'h1;
        M_alu_alufn = 6'h20;
        M_dl_temp_d = M_alu_out;
      end
      2'h2: begin
        M_alu_a = cursor;
        M_alu_b = 1'h1;
        M_alu_alufn = 6'h21;
        M_ur_temp_d = M_alu_out;
      end
      2'h3: begin
        M_alu_a = cursor;
        M_alu_b = 3'h7;
        M_alu_alufn = 6'h21;
        M_dr_temp_d = M_alu_out;
      end
      default: begin
        M_alu_a = 25'h0000000;
        M_alu_b = 25'h0000000;
        M_alu_alufn = 6'h00;
      end
    endcase
    
    case (M_cursor_position_q)
      1'h0: begin
        up_left = M_ul_temp_q;
        down_left = M_dl_temp_q;
        up_right = 25'h0000000;
        down_right = 25'h0000000;
      end
      1'h1: begin
        up_left = M_ul_temp_q;
        down_left = M_dl_temp_q;
        up_right = 25'h0000000;
        down_right = 25'h0000000;
      end
      2'h2: begin
        up_left = M_ul_temp_q;
        down_left = M_dl_temp_q;
        up_right = 25'h0000000;
        down_right = 25'h0000000;
      end
      2'h3: begin
        up_left = M_ul_temp_q;
        down_left = 25'h0000000;
        up_right = M_ur_temp_q;
        down_right = 25'h0000000;
      end
      3'h4: begin
        up_left = M_ul_temp_q;
        down_left = M_dl_temp_q;
        up_right = 25'h0000000;
        down_right = 25'h0000000;
      end
      3'h5: begin
        up_left = M_ul_temp_q;
        down_left = M_dl_temp_q;
        up_right = M_ur_temp_q;
        down_right = 25'h0000000;
      end
      3'h6: begin
        up_left = M_ul_temp_q;
        down_left = 25'h0000000;
        up_right = M_ur_temp_q;
        down_right = 25'h0000000;
      end
      3'h7: begin
        up_left = M_ul_temp_q;
        down_left = M_dl_temp_q;
        up_right = 25'h0000000;
        down_right = M_dr_temp_q;
      end
      4'ha: begin
        up_left = M_ul_temp_q;
        down_left = 25'h0000000;
        up_right = M_ur_temp_q;
        down_right = M_dr_temp_q;
      end
      4'hb: begin
        up_left = M_ul_temp_q;
        down_left = M_dl_temp_q;
        up_right = 25'h0000000;
        down_right = M_dr_temp_q;
      end
      4'hd: begin
        up_left = M_ul_temp_q;
        down_left = 25'h0000000;
        up_right = M_ur_temp_q;
        down_right = M_dr_temp_q;
      end
      4'he: begin
        up_left = M_ul_temp_q;
        down_left = M_dl_temp_q;
        up_right = 25'h0000000;
        down_right = M_dr_temp_q;
      end
      5'h11: begin
        up_left = M_ul_temp_q;
        down_left = 25'h0000000;
        up_right = M_ur_temp_q;
        down_right = M_dr_temp_q;
      end
      5'h12: begin
        up_left = 25'h0000000;
        down_left = M_dl_temp_q;
        up_right = 25'h0000000;
        down_right = M_dr_temp_q;
      end
      5'h13: begin
        up_left = 25'h0000000;
        down_left = M_dl_temp_q;
        up_right = M_ur_temp_q;
        down_right = M_dr_temp_q;
      end
      5'h14: begin
        up_left = 25'h0000000;
        down_left = 25'h0000000;
        up_right = M_ur_temp_q;
        down_right = M_dr_temp_q;
      end
      5'h15: begin
        up_left = 25'h0000000;
        down_left = M_dl_temp_q;
        up_right = 25'h0000000;
        down_right = M_dr_temp_q;
      end
      5'h16: begin
        up_left = 25'h0000000;
        down_left = M_dl_temp_q;
        up_right = M_ur_temp_q;
        down_right = M_dr_temp_q;
      end
      5'h17: begin
        up_left = 25'h0000000;
        down_left = M_dl_temp_q;
        up_right = M_ur_temp_q;
        down_right = M_dr_temp_q;
      end
      5'h18: begin
        up_left = 25'h0000000;
        down_left = 25'h0000000;
        up_right = M_ur_temp_q;
        down_right = M_dr_temp_q;
      end
      default: begin
        up_left = M_ul_temp_q;
        down_left = M_dl_temp_q;
        up_right = M_ur_temp_q;
        down_right = M_dr_temp_q;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
      M_ul_temp_q <= 1'h0;
      M_dl_temp_q <= 1'h0;
      M_ur_temp_q <= 1'h0;
      M_dr_temp_q <= 1'h0;
      M_cursor_position_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
      M_ul_temp_q <= M_ul_temp_d;
      M_dl_temp_q <= M_dl_temp_d;
      M_ur_temp_q <= M_ur_temp_d;
      M_dr_temp_q <= M_dr_temp_d;
      M_cursor_position_q <= M_cursor_position_d;
    end
  end
  
endmodule
