/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_26 (
    input z,
    input v,
    input n,
    input [5:0] alufn,
    output reg [24:0] out
  );
  
  
  
  reg lsb;
  
  always @* begin
    
    case (alufn[1+1-:2])
      2'h1: begin
        lsb = z;
      end
      2'h2: begin
        lsb = n ^ v;
      end
      2'h3: begin
        lsb = z | (n ^ v);
      end
      default: begin
        lsb = 1'h0;
      end
    endcase
    out = {24'h000000, lsb};
  end
endmodule
