/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module get_position_15 (
    input [24:0] cursor,
    output reg [4:0] pos
  );
  
  
  
  always @* begin
    
    case (cursor)
      25'h0000001: begin
        pos = 1'h0;
      end
      25'h0000002: begin
        pos = 1'h1;
      end
      25'h0000004: begin
        pos = 2'h2;
      end
      25'h0000008: begin
        pos = 2'h3;
      end
      25'h0000010: begin
        pos = 3'h4;
      end
      25'h0000020: begin
        pos = 3'h5;
      end
      25'h0000040: begin
        pos = 3'h6;
      end
      25'h0000080: begin
        pos = 3'h7;
      end
      25'h0000100: begin
        pos = 4'h8;
      end
      25'h0000200: begin
        pos = 4'h9;
      end
      25'h0000400: begin
        pos = 4'ha;
      end
      25'h0000800: begin
        pos = 4'hb;
      end
      25'h0001000: begin
        pos = 4'hc;
      end
      25'h0002000: begin
        pos = 4'hd;
      end
      25'h0004000: begin
        pos = 4'he;
      end
      25'h0008000: begin
        pos = 4'hf;
      end
      25'h0010000: begin
        pos = 5'h10;
      end
      25'h0020000: begin
        pos = 5'h11;
      end
      25'h0040000: begin
        pos = 5'h12;
      end
      25'h0080000: begin
        pos = 5'h13;
      end
      25'h0100000: begin
        pos = 5'h14;
      end
      25'h0200000: begin
        pos = 5'h15;
      end
      25'h0400000: begin
        pos = 5'h16;
      end
      25'h0800000: begin
        pos = 5'h17;
      end
      25'h1000000: begin
        pos = 5'h18;
      end
      default: begin
        pos = 1'h0;
      end
    endcase
  end
endmodule
