/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module check_lighted_21 (
    input clk,
    input rst,
    input [24:0] cursor,
    input [24:0] map,
    output reg out
  );
  
  
  
  reg [24:0] temp;
  
  wire [25-1:0] M_alu_out;
  reg [25-1:0] M_alu_a;
  reg [25-1:0] M_alu_b;
  reg [6-1:0] M_alu_alufn;
  alu_37 alu (
    .a(M_alu_a),
    .b(M_alu_b),
    .alufn(M_alu_alufn),
    .out(M_alu_out)
  );
  
  always @* begin
    M_alu_a = cursor;
    M_alu_b = map;
    M_alu_alufn = 6'h18;
    temp = M_alu_out;
    if (temp == cursor) begin
      out = 1'h1;
    end else begin
      out = 1'h0;
    end
  end
endmodule
