/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module decimal2_24 (
    input [7:0] a,
    output reg [3:0] out1,
    output reg [3:0] out0
  );
  
  
  
  always @* begin
    if (a <= 4'h9) begin
      out1 = 4'h0;
      out0 = a[0+3-:4];
    end else begin
      if (a > 4'h9 && a <= 5'h13) begin
        out1 = 4'h1;
        out0 = a - 4'ha;
      end else begin
        if (a > 5'h13 && a <= 5'h1d) begin
          out1 = 4'h2;
          out0 = a - 5'h14;
        end else begin
          if (a > 5'h1d && a <= 6'h27) begin
            out1 = 4'h3;
            out0 = a - 5'h1e;
          end else begin
            if (a > 6'h27 && a <= 6'h31) begin
              out1 = 4'h4;
              out0 = a - 6'h28;
            end else begin
              if (a > 6'h31 && a <= 6'h3b) begin
                out1 = 4'h5;
                out0 = a - 6'h32;
              end else begin
                if (a > 6'h3b && a <= 7'h45) begin
                  out1 = 4'h6;
                  out0 = a - 6'h3c;
                end else begin
                  if (a > 7'h45 && a <= 7'h4f) begin
                    out1 = 4'h7;
                    out0 = a - 7'h46;
                  end else begin
                    if (a > 7'h4f && a <= 7'h59) begin
                      out1 = 4'h8;
                      out0 = a - 7'h50;
                    end else begin
                      if (a > 7'h59 && a <= 7'h63) begin
                        out1 = 4'h9;
                        out0 = a - 7'h5a;
                      end else begin
                        if (a > 7'h63 && a <= 7'h6d) begin
                          out1 = 4'h0;
                          out0 = a - 7'h64;
                        end else begin
                          out1 = 1'h0;
                          out0 = 1'h0;
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
  end
endmodule
