/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module gen_map_temp_22 (
    input mask_type,
    input game_type,
    output reg [24:0] out
  );
  
  
  
  always @* begin
    out = 25'h0000000;
    if (mask_type == 1'h0 && game_type == 1'h0) begin
      out = 25'h0000032;
    end else begin
      if (mask_type == 1'h1 && game_type == 1'h0) begin
        out = 25'h009ab20;
      end else begin
        if (mask_type == 1'h0 && game_type == 1'h1) begin
          out = 25'h18c8996;
        end else begin
          if (mask_type == 1'h1 && game_type == 1'h1) begin
            out = 25'h0d2c49e;
          end
        end
      end
    end
  end
endmodule
