/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    input start_button,
    input reset_button,
    output reg [24:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  reg [24:0] out_temp;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [8-1:0] M_processor_display_seg0;
  wire [8-1:0] M_processor_display_seg1;
  wire [8-1:0] M_processor_display_seg2;
  wire [8-1:0] M_processor_display_seg3;
  wire [25-1:0] M_processor_out;
  reg [5-1:0] M_processor_button;
  reg [1-1:0] M_processor_start_button;
  reg [1-1:0] M_processor_reset_button;
  processor_2 processor (
    .clk(clk),
    .rst(rst),
    .button(M_processor_button),
    .start_button(M_processor_start_button),
    .reset_button(M_processor_reset_button),
    .display_seg0(M_processor_display_seg0),
    .display_seg1(M_processor_display_seg1),
    .display_seg2(M_processor_display_seg2),
    .display_seg3(M_processor_display_seg3),
    .out(M_processor_out)
  );
  wire [2-1:0] M_seven_seg_ctr_value;
  counter_3 seven_seg_ctr (
    .clk(clk),
    .rst(rst),
    .value(M_seven_seg_ctr_value)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 25'h0000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_processor_button = io_button;
    M_processor_start_button = start_button;
    M_processor_reset_button = reset_button;
    M_processor_button = io_button;
    out_temp = M_processor_out;
    io_led = out_temp;
    
    case (M_seven_seg_ctr_value)
      1'h0: begin
        io_seg = M_processor_display_seg0;
        io_sel = 4'h1;
      end
      1'h1: begin
        io_seg = M_processor_display_seg1;
        io_sel = 4'h2;
      end
      2'h2: begin
        io_seg = M_processor_display_seg2;
        io_sel = 4'h4;
      end
      2'h3: begin
        io_seg = M_processor_display_seg3;
        io_sel = 4'h8;
      end
      default: begin
        io_seg = M_processor_display_seg0;
        io_sel = 4'h1;
      end
    endcase
  end
endmodule
