/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_26 (
    input [4:0] char,
    output reg [7:0] segs
  );
  
  
  
  always @* begin
    
    case (char)
      1'h0: begin
        segs = 8'hbf;
      end
      1'h1: begin
        segs = 8'h06;
      end
      2'h2: begin
        segs = 8'hdb;
      end
      2'h3: begin
        segs = 8'h4f;
      end
      3'h4: begin
        segs = 8'h66;
      end
      3'h5: begin
        segs = 8'h6d;
      end
      3'h6: begin
        segs = 8'hfd;
      end
      3'h7: begin
        segs = 8'h07;
      end
      4'h8: begin
        segs = 8'hff;
      end
      4'h9: begin
        segs = 8'h67;
      end
      4'ha: begin
        segs = 8'hf7;
      end
      4'hb: begin
        segs = 8'hfc;
      end
      4'hc: begin
        segs = 8'hb9;
      end
      4'hd: begin
        segs = 8'hde;
      end
      4'he: begin
        segs = 8'hf9;
      end
      4'hf: begin
        segs = 8'hf1;
      end
      5'h10: begin
        segs = 8'hf6;
      end
      5'h11: begin
        segs = 8'hb8;
      end
      5'h12: begin
        segs = 8'hb7;
      end
      5'h13: begin
        segs = 8'hf3;
      end
      5'h14: begin
        segs = 8'hd0;
      end
      5'h15: begin
        segs = 8'hed;
      end
      5'h16: begin
        segs = 8'hbe;
      end
      5'h17: begin
        segs = 8'h00;
      end
      default: begin
        segs = 8'h00;
      end
    endcase
  end
endmodule
